import markov_semigroups_applications_diffusion_processes_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace markov_semigroups_applications_diffusion_processes_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end markov_semigroups_applications_diffusion_processes_theorem_canonical_lane_mathlib
end HautevilleHouse
